=== ptoribi/lightning/lightning-xml-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="container" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="interface" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="default_ip" type="xs:string" minOccurs="0"  maxOccurs="unbounded"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="enable_ipv6" default="yes">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="yes"/>
                        <xs:enumeration value="no"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="rpath_filter" default="yes">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="yes"/>
                        <xs:enumeration value="no"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="link_local_ipv6" default="yes">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="yes"/>
                        <xs:enumeration value="no"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="connected_to_physical_interface" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="hostname" type="xs:string"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="network" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="container" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="interface" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ip" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" default="switch">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="switch"/>
                  <xs:enumeration value="hub"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ptoribi/lightning/scenarios/RSC/S12.xml
<?xml version="1.0" encoding="UTF-8" ?>

<scenario description="RSC: Escenario práctica sesión 12"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lightning-xml-schema.xsd">

  <container name="PCA" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="PCB" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="RA" type="router">
    <interface name="eth0.0" enable_ipv6="yes">
      <default_ip>192.168.0.1/24</default_ip>
    </interface>
    <interface name="eth0.1" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.1.1/24</default_ip>
    </interface>
    <interface name="eth0.2" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.2.1/24</default_ip>
    </interface>
    <interface name="eth0.3" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.3.1/24</default_ip>
    </interface>
    <interface name="eth0.4" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.4.1/24</default_ip>
    </interface>
    <interface name="wlan0" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.5.1/24</default_ip>
    </interface>
  </container>
  
  <container name="RB" type="router">
    <interface name="eth0.0" enable_ipv6="yes">
      <default_ip>192.168.0.1/24</default_ip>
    </interface>
    <interface name="eth0.1" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.1.1/24</default_ip>
    </interface>
    <interface name="eth0.2" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.2.1/24</default_ip>
    </interface>
    <interface name="eth0.3" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.3.1/24</default_ip>
    </interface>
    <interface name="eth0.4" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.4.1/24</default_ip>
    </interface>
    <interface name="wlan0" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.5.1/24</default_ip>
    </interface>
  </container>
  
  
  <network name="RedA" type="switch">
    
    <container name="PCA">
      <interface name="eth1">
        <ip>192.100.100.101/24</ip>
      </interface>
    </container>
    
    <container name="RA">
      <interface name="eth0.0"/>
    </container>
    
  </network>
  
  
  <network name="RedB" type="switch">
    
    <container name="PCB">
      <interface name="eth1">
        <ip>192.100.100.102/24</ip>
      </interface>
    </container>
    
    <container name="RB">
      <interface name="eth0.0"/>
    </container>
    
  </network>
  
  
  <network name="RedR" type="switch">
    
    <container name="RA">
      <interface name="eth0.1"/>
    </container>
    
    <container name="RB">
      <interface name="eth0.1"/>
    </container>
    
  </network>
    
</scenario>

=== ptoribi/lightning/scenarios/RYSCA/simple.xml
<?xml version="1.0" encoding="UTF-8" ?>

<scenario description="RYSCA: Escenario simple con 2 PCs (Ãºtil para pruebas de desarrollo con librawnet)"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lightning-xml-schema.xsd">

  <container name="hostX" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="hostY" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  
  <network name="Red1" type="switch">
    
    <container name="hostX">
      <interface name="eth1">
        <ip>192.100.100.101/24</ip>
      </interface>
    </container>
    
    <container name="hostY">
      <interface name="eth1">
        <ip>192.100.100.102/24</ip>
      </interface>
    </container>
    
  </network>
  
  
</scenario>

=== ptoribi/lightning/scenarios/RSC/S16_escenario_2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<scenario description="RSC: Escenario 2 práctica sesión 16"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lightning-xml-schema.xsd">

  <container name="PCA1" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="PCB1" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="PCA2" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="PCB2" type="host">
    <interface name="eth1" enable_ipv6="yes" link_local_ipv6="no"/>
  </container>
  
  <container name="RA1" type="router">
    <interface name="eth0.0" enable_ipv6="yes">
      <default_ip>192.168.0.1/24</default_ip>
    </interface>
    <interface name="eth0.1" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.1.1/24</default_ip>
    </interface>
    <interface name="eth0.2" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.2.1/24</default_ip>
    </interface>
    <interface name="eth0.3" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.3.1/24</default_ip>
    </interface>
    <interface name="eth0.4" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.4.1/24</default_ip>
    </interface>
    <interface name="wlan0" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.5.1/24</default_ip>
    </interface>
  </container>
  
  <container name="RB1" type="router">
    <interface name="eth0.0" enable_ipv6="yes">
      <default_ip>192.168.0.1/24</default_ip>
    </interface>
    <interface name="eth0.1" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.1.1/24</default_ip>
    </interface>
    <interface name="eth0.2" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.2.1/24</default_ip>
    </interface>
    <interface name="eth0.3" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.3.1/24</default_ip>
    </interface>
    <interface name="eth0.4" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.4.1/24</default_ip>
    </interface>
    <interface name="wlan0" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.5.1/24</default_ip>
    </interface>
  </container>
  
  <container name="RA2" type="router">
    <interface name="eth0.0" enable_ipv6="yes">
      <default_ip>192.168.0.1/24</default_ip>
    </interface>
    <interface name="eth0.1" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.1.1/24</default_ip>
    </interface>
    <interface name="eth0.2" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.2.1/24</default_ip>
    </interface>
    <interface name="eth0.3" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.3.1/24</default_ip>
    </interface>
    <interface name="eth0.4" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.4.1/24</default_ip>
    </interface>
    <interface name="wlan0" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.5.1/24</default_ip>
    </interface>
  </container>
  
  <container name="RB2" type="router">
    <interface name="eth0.0" enable_ipv6="yes">
      <default_ip>192.168.0.1/24</default_ip>
    </interface>
    <interface name="eth0.1" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.1.1/24</default_ip>
    </interface>
    <interface name="eth0.2" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.2.1/24</default_ip>
    </interface>
    <interface name="eth0.3" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.3.1/24</default_ip>
    </interface>
    <interface name="eth0.4" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.4.1/24</default_ip>
    </interface>
    <interface name="wlan0" enable_ipv6="yes" link_local_ipv6="no">
      <default_ip>192.168.5.1/24</default_ip>
    </interface>
  </container>
  
  
  <network name="RedA1" type="switch">
    
    <container name="PCA1">
      <interface name="eth1">
        <ip>192.100.100.101/24</ip>
      </interface>
    </container>
    
    <container name="RA1">
      <interface name="eth0.0"/>
    </container>
    
  </network>
  
  
  <network name="RedB1" type="switch">
    
    <container name="PCB1">
      <interface name="eth1">
        <ip>192.100.100.102/24</ip>
      </interface>
    </container>
    
    <container name="RB1">
      <interface name="eth0.0"/>
    </container>
    
  </network>
  
  
  <network name="RedA1B1" type="switch">
    
    <container name="RA1">
      <interface name="eth0.1"/>
    </container>
    
    <container name="RB1">
      <interface name="eth0.1"/>
    </container>
    
  </network>
  
  
  <network name="RedA1A2" type="switch">
    
    <container name="RA1">
      <interface name="eth0.2"/>
    </container>
    
    <container name="RA2">
      <interface name="eth0.2"/>
    </container>
    
  </network>
  
  
  <network name="RedB1B2" type="switch">
    
    <container name="RB1">
      <interface name="eth0.2"/>
    </container>
    
    <container name="RB2">
      <interface name="eth0.2"/>
    </container>
    
  </network>
  

  <network name="RedA2B2" type="switch">
    
    <container name="RA2">
      <interface name="eth0.1"/>
    </container>
    
    <container name="RB2">
      <interface name="eth0.1"/>
    </container>
    
  </network>
  
  
  <network name="RedA2" type="switch">
    
    <container name="PCA2">
      <interface name="eth1">
        <ip>192.100.100.103/24</ip>
      </interface>
    </container>
    
    <container name="RA2">
      <interface name="eth0.0"/>
    </container>
    
  </network>
  
  
  <network name="RedB2" type="switch">
    
    <container name="PCB2">
      <interface name="eth1">
        <ip>192.100.100.104/24</ip>
      </interface>
    </container>
    
    <container name="RB2">
      <interface name="eth0.0"/>
    </container>
    
  </network>
  
</scenario>
